### PR TITLE
Fix birthdays bug

### LINKED ISSUE #524: Bug with birthday dates
The birthdays are displayed on the day before. This is because the birthdays are stored in UTC in the database (meaning that it is stored as 23:00 in the day before), and the filtering is done with extracting the day and month directly from the DB, without conversion.

### PR DESCRIPTION
**Pull request by Mathieu414**

### CODE REVIEW

File: app/pages/events/event_list/event_list.php [hunk 1]
```diff
@@ -12,18 +12,23 @@
...
-// Query the database to get a list of users whose birthday matches the current date
-$birthday_users = em()->createQueryBuilder()
+// Fetch users whose birthday is today
+$all_users = em()->createQueryBuilder()
     ->select("u")
     ->from(User::class, "u")
-    ->where("MONTH(u.birthdate) = :month AND DAY(u.birthdate) = :day")
-    ->setParameter("month", $current_date_month)
-    ->setParameter("day", $current_date_day)
+    ->where("u.birthdate IS NOT NULL")
```
Comment (Atmos4) [inline app/pages/events/event_list/event_list.php]: A bit extreme to fetch all users. Maybe in a range ?

Comment (Mathieu414) [reply app/pages/events/event_list/event_list.php]: Done, filtered to previous and next month users to keep it simple.

File: app/pages/events/event_list/event_list.php [hunk 2]
```diff
@@ -12,18 +12,30 @@
...
-$current_date_month = date('m');
-$current_date_day = date('d');
+$current_date = new DateTime('now');
+$current_month_day = $current_date->format('m-d');
 
-// Query the database to get a list of users whose birthday matches the current date
-$birthday_users = em()->createQueryBuilder()
+$current_month = $current_date->format('m');
+$prev_month = $current_month == '01' ? '12' : str_pad((int) $current_month - 1, 2, '0', STR_PAD_LEFT);
+$next_month = $current_month == '12' ? '01' : str_pad((int) $current_month + 1, 2, '0', STR_PAD_LEFT);
```
Comment (Atmos4) [inline app/pages/events/event_list/event_list.php]: This is very ugly 😅
You can be a lot cleaner by manipulating the datetime object directly.
I think this ok enough so I'll approve

**Review by Atmos4 — APPROVED** [review]

File: app/pages/events/event_list/event_list.php (hunk 2 above)
Comment (Mathieu414) [reply app/pages/events/event_list/event_list.php]: Did a small fix for that. Hopefully a bit better, even though I'm struggling to find a good solution 😪
